version: 0.2

env:
  exported-variables:
    - REACT_APP_BuildENV

phases:
  install:
    runtime-versions:
      nodejs: 12
    commands:
      - yarn install

  build:
    commands:
      - yarn build

artifacts:
  type: zip
  files:
    - '**/*'
  base-directory: build