version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 12
    commands:
      - yarn install

  build:
    commands:
      - yarn build

artifacts:
  files:
    - '**/*'
  base-directory: build