/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "eu-west-2",
    "aws_cognito_identity_pool_id": "eu-west-2:74c372e5-24a1-432f-ae0e-30c4a9f15012",
    "aws_cognito_region": "eu-west-2",
    "aws_user_pools_id": "eu-west-2_8GjbfJ9Ct",
    "aws_user_pools_web_client_id": "u53qbta3dfjv74kfj9oeakujg",
    "oauth": {
        "domain": "localing-prod.auth.eu-west-2.amazoncognito.com",
        "scope": [
            "phone",
            "email",
            "openid",
            "profile",
            "aws.cognito.signin.user.admin"
        ],
        "redirectSignIn": "http://localhost:3000/",
        "redirectSignOut": "http://localhost:3000/",
        "responseType": "code"
    },
    "federationTarget": "COGNITO_USER_POOLS"
};


export default awsmobile;
